---
abstract: 'a flat-text database for shell scripting'
author:
  - 'John Heidemann <johnh@isi.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302'
license: GPL-2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fsdb
no_index:
  directory:
    - t
    - inc
requires:
  HTML::Parser: 0
  Test::More: 0
  Text::CSV_XS: 0
  threads: 1
version: 2.37
